apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ghostgpu
  name: ghostgpu-gpupool-admin-role
rules:
- apiGroups:
  - ghostgpu.dev
  resources:
  - gpupools
  verbs:
  - '*'
- apiGroups:
  - ghostgpu.dev
  resources:
  - gpupools/status
  verbs:
  - get
