apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: gpu-metrics
    app.kubernetes.io/name: ghostgpu
  name: ghostgpu-gpu-metrics
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: gpu-metrics
    port: 9400
    protocol: TCP
    targetPort: gpu-metrics
  selector:
    app.kubernetes.io/name: ghostgpu
    control-plane: controller-manager
  type: ClusterIP
